
@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@contentType = application/json
@token = {{login.response.body.token}}

### -----------------------------------------------------------

# @name login
POST http://{{host}}/user/login
Content-Type: {{contentType}}

{
    "email":"kaung@gmail.com",
    "password":"111111"
}

### -----------------------------------------------------------

# @name addComment
POST http://{{host}}/comment/
Content-Type: {{contentType}}
x-jwt: {{token}}

{
    "postId":33,
    "text":"hote loh lar by kaung"
}

### -----------------------------------------------------------

# @name getComment
GET http://{{host}}/comment/33
Content-Type: {{contentType}}
x-jwt: {{token}}

### -----------------------------------------------------------

# @name getCommentByPostId
GET http://{{host}}/comment/post/33
Content-Type: {{contentType}}
x-jwt: {{token}}

### -----------------------------------------------------------

# @name updateComment
PATCH  http://{{host}}/comment/5
Content-Type: {{contentType}}
x-jwt: {{token}}

{
    "text":"comment updated by arkar"
}
### -----------------------------------------------------------

# @name deleteCommentById
DELETE   http://{{host}}/comment/1
Content-Type: {{contentType}}
x-jwt: {{token}}
